version: "3.0"
services:
  webhook:
    build: .
    ports:
      - "5000:80"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      SG_HOST: https://<yoursite>.shotgunstudio.com
      SG_SCRIPT_NAME: <your_script>
      SG_SCRIPT_KEY: <your_key>
    volumes:
      - ./:/app
